name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        check-latest: true
        cache: true

    - name: Install dependencies
      run: make deps

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54.2
        args: --timeout=5m

    - name: Lint
      run: make lint
      continue-on-error: true  # Temporarily allow lint errors to not block the workflow

    - name: Test
      run: make test

    - name: Race condition tests
      run: make test-race

    - name: E2E Tests
      run: make e2e-test

    - name: Test Coverage
      run: make test-cover

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.html

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
        include:
          - goos: linux
            goarch: amd64
            platform: linux-amd64
          - goos: linux
            goarch: arm64
            platform: linux-arm64
          - goos: darwin
            goarch: amd64
            platform: darwin-amd64
          - goos: darwin
            goarch: arm64
            platform: darwin-arm64

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true
          cache: true

      - name: Install dependencies
        run: make deps

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p build
          go build -o build/exchange-connector-${{ matrix.platform }} ./cmd/examples
          chmod +x build/exchange-connector-${{ matrix.platform }}

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: exchange-connector-${{ matrix.platform }}
          path: build/exchange-connector-${{ matrix.platform }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Setup GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Generate release tag
        id: tag
        run: |
          VERSION=$(cat VERSION 2>/dev/null || echo "v0.1.0")
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p release
          cp artifacts/exchange-connector-linux-amd64/exchange-connector-linux-amd64 release/
          cp artifacts/exchange-connector-linux-arm64/exchange-connector-linux-arm64 release/
          cp artifacts/exchange-connector-darwin-amd64/exchange-connector-darwin-amd64 release/
          cp artifacts/exchange-connector-darwin-arm64/exchange-connector-darwin-arm64 release/
          
          # Create release notes
          echo "# Exchange Connector Release ${{ steps.tag.outputs.version }}" > release_notes.md
          echo "Released on ${{ steps.tag.outputs.date }}" >> release_notes.md
          echo "" >> release_notes.md
          echo "## Included builds" >> release_notes.md
          echo "- Linux (AMD64)" >> release_notes.md
          echo "- Linux (ARM64)" >> release_notes.md
          echo "- macOS (AMD64)" >> release_notes.md
          echo "- macOS (ARM64/Apple Silicon)" >> release_notes.md
          
          # Create release using GitHub CLI
          gh release create ${{ steps.tag.outputs.version }} \
            --title "Exchange Connector ${{ steps.tag.outputs.version }}" \
            --notes-file release_notes.md \
            release/exchange-connector-linux-amd64 \
            release/exchange-connector-linux-arm64 \
            release/exchange-connector-darwin-amd64 \
            release/exchange-connector-darwin-arm64 