name: CI

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        check-latest: true
        cache: true

    - name: Install dependencies
      run: make deps

    # Linting is disabled due to Go 1.24 compatibility issues
    # - name: Install golangci-lint
    #   uses: golangci/golangci-lint-action@v4
    #   with:
    #     version: v1.54.2
    #     args: --timeout=5m
    #     skip-cache: true  # Skip using cache to avoid file exists errors

    # - name: Lint
    #   run: make lint
    #   continue-on-error: true  # Temporarily allow lint errors to not block the workflow

    - name: Test
      run: make test

    - name: Race condition tests
      run: make test-race


  # Build job removed - not needed for library releases

  release:
    needs: test # Depend on the test job
    runs-on: ubuntu-latest
    # Run only on tag pushes
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5 # Use the latest major version
        with:
          # Optional: specify the version of goreleaser to use, otherwise latest is used
          # version: latest
          args: release --clean # Use --clean to ensure a clean build environment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Set other environment variables if needed by your goreleaser config